# Generated by Django 5.2.5 on 2025-08-25 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assignee_email_task_assignee_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(choices=[('Create a document for Adult classes', 'Create a document for Adult classes'), ('Organize cultural event', 'Organize cultural event'), ('Coordinate volunteer training', 'Coordinate volunteer training'), ('Manage social media accounts', 'Manage social media accounts'), ('Prepare presentation materials', 'Prepare presentation materials'), ('Coordinate fundraising campaign', 'Coordinate fundraising campaign'), ('Organize community outreach', 'Organize community outreach'), ('Manage website content', 'Manage website content'), ('Coordinate language classes', 'Coordinate language classes'), ('Organize youth programs', 'Organize youth programs'), ('Other', 'Other')], default='Create a document for Adult classes', max_length=200),
        ),
    ]
